FROM node:20.11.1-alpine3.19 AS builder
WORKDIR /app
COPY src/package*.json ./
RUN npm install && npm cache clean --force
ENV PATH=/app/node_modules/.bin:$PATH
COPY src .
EXPOSE 3011
CMD ["npm", "run", "dev"]